# Generated by Django 3.1.2 on 2020-11-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteiraVirtual', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compra',
            new_name='CompraCartao',
        ),
        migrations.CreateModel(
            name='CompraCarteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteiraVirtual.carteira')),
            ],
        ),
    ]
